theme = "semi-native"

[icons]
name = "awesome5"
[icons.overrides]
time = ""

### LAPTOP
[[block]]
block = "battery"
format = "{percentage}"
### LAPTOP

[[block]]
block = "time"
format = "%a %d/%m %R"
