[theme]
theme = "semi-native"
[theme.overrides]
idle_fg = "#c8ccd4"
info_fg = "#c8ccd4"
good_fg = "#98c379"
warning_fg = "#e5c07b"
critical_fg = "#e06c75"
[icons]
icons = "material-nf"
[icons.overrides]
time = ""

### LAPTOP
[[block]]
block = "battery"
format = "$icon $percentage"
### LAPTOP

[[block]]
block = "rofication"
interval = 1
socket_path = "/run/user/1000/nofi/socket"

[[block]]
block = "pomodoro"

[[block]]
block = "time"
format = "$timestamp.datetime(f:'%R') UTC"
timezone = "UTC"

[[block]]
block = "time"
format = "$timestamp.datetime(f:'%a %d/%m %R')"
