[theme]
theme = "semi-native"
[icons]
icons = "awesome5"
[icons.overrides]
time = ""

### LAPTOP
[[block]]
block = "battery"
format = "$icon $percentage"
### LAPTOP

[[block]]
block = "time"
format = "$timestamp.datetime(f:'%R') UTC"
timezone = "UTC"

[[block]]
block = "time"
format = "$timestamp.datetime(f:'%a %d/%m %R')"
