---
- hosts: 127.0.0.1
  connection: local
  vars:
    laptop: "{{ lookup('env', 'LAPTOP') | bool }}"
  tasks:
    - name: /etc/X11/xorg.conf.d
      file:
        path: /etc/X11/xorg.conf.d
        owner: root
        group: root
        mode: '0755'
        state: directory
      become: true
    - name: Intel graphics configuration
      template:
        src: ./templates/10-intel.conf
        dest: /etc/X11/xorg.conf.d/10-intel.conf
        owner: root
        group: root
        mode: '0644'
      become: true
      when: laptop
    - name: Mouse/trackpad configuration
      template:
        src: ./templates/20-mouse.conf
        dest: /etc/X11/xorg.conf.d/20-mouse.conf
        owner: root
        group: root
        mode: '0644'
      become: true
    - name: Keyboard configuration
      template:
        src: ./templates/30-keyboard.conf
        dest: /etc/X11/xorg.conf.d/30-keyboard.conf
        owner: root
        group: root
        mode: '0644'
      become: true
    - name: /etc/systemd/system/getty@tty1.service.d
      file:
        path: /etc/systemd/system/getty@tty1.service.d
        owner: root
        group: root
        mode: '0755'
        state: directory
      become: true
    - name: Auto login configuration
      template:
        src: ./templates/systemd/system/getty@tty1.service.d/override.conf
        dest: /etc/systemd/system/getty@tty1.service.d/override.conf
        owner: root
        group: root
        mode: '0644'
      become: true
    - name: Liquid cooler configuration file
      template:
        src: ./templates/systemd/system/liquidcfg.service
        dest: /etc/systemd/system/liquidcfg.service
        owner: root
        group: root
        mode: '0644'
      become: true
      when: not laptop
    - name: Reload systemd
      systemd:
        daemon_reload: true
      become: true
    - name: Liquid cooler configuration service
      service:
        name: liquidcfg
        state: started
        enabled: true
      become: true
      when: not laptop
    - name: Install Pacman packages
      pacman:
        name: "{{ lookup('file', '../setup/pacman').splitlines() }}"
        state: present
      become: true
    - name: Install laptop-specific Pacman packages
      pacman:
        name:
          - fprint
          - intel-ucode
          - mesa
          - xf86-video-intel
        state: present
      when: laptop
    - name: Install desktop-specific Pacman packages
      pacman:
        name:
          - amd-ucode
          - nvidia
          - nvidia-settings
        state: present
      when: not laptop
      become: true
