---
- hosts: 127.0.0.1
  connection: local
  vars:
    laptop: "{{ lookup('env', 'LAPTOP') | bool }}"
    vm: "{{ lookup('env', 'VM_TEST') | bool }}"
  tasks:
    - name: Remove unused packages
      pacman:
        name:
          - asdf-vm
          - exfat-utils
          - gparted
          - network-manager-applet
          - networkmanager
          - networkmanager-openvpn
          - nvidia
          - nvidia-settings
          - openvpn
          - pulseaudio
          - pulseaudio-alsa
          - pulseaudio-bluetooth
          - task
          - ttf-font-awesome
          - ttf-hack-nerd
          - xbacklight
          - xf86-video-amdgpu
          - xf86-video-intel
        state: absent
      become: true
    - name: Install laptop-specific Pacman packages
      pacman:
        name:
          - acpilight
          - fprint
          - intel-media-driver
          - intel-ucode
          - sof-firmware
          - tlp
        state: present
      become: true
      when:
        - laptop
        - not vm
    - name: Install desktop-specific Pacman packages
      pacman:
        name:
          - amd-ucode
          - liquidctl
          - vulkan-radeon
        state: present
      when:
        - not laptop
        - not vm
      become: true
    - name: Install Pacman packages
      pacman:
        name: "{{ lookup('file', '../setup/pacman').splitlines() }}"
        state: present
      become: true
    - name: /etc/X11/xorg.conf.d
      file:
        path: /etc/X11/xorg.conf.d
        owner: root
        group: root
        mode: "0755"
        state: directory
      become: true
    - name: Ensure group "video" exists
      ansible.builtin.group:
        name: video
        state: present
    - name: Add self to video group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: video
        append: yes
      become: true
    - name: Backlight configuration
      template:
        src: ./templates/udev/rules.d/90-backlight.rules
        dest: /etc/udev/rules.d/90-backlight.rules
        owner: root
        group: root
        mode: "0644"
      become: true
      when:
        - laptop
        - not vm
    - name: AMD Graphics Configuration
      template:
        src: ./templates/X11/xorg.conf.d/10-amdgpu.conf
        dest: /etc/X11/xorg.conf.d/10-amdgpu.conf
        owner: root
        group: root
        mode: "0644"
      become: true
      when:
        - not laptop
        - not vm
    - name: Intel graphics configuration
      template:
        src: ./templates/X11/xorg.conf.d/10-intelgpu.conf
        dest: /etc/X11/xorg.conf.d/10-intelgpu.conf
        owner: root
        group: root
        mode: "0644"
      become: true
      when:
        - laptop
    - name: Mouse/trackpad configuration
      template:
        src: ./templates/X11/xorg.conf.d/20-mouse.conf
        dest: /etc/X11/xorg.conf.d/20-mouse.conf
        owner: root
        group: root
        mode: "0644"
      become: true
    - name: Keyboard configuration
      template:
        src: ./templates/X11/xorg.conf.d/30-keyboard.conf
        dest: /etc/X11/xorg.conf.d/30-keyboard.conf
        owner: root
        group: root
        mode: "0644"
      become: true
    - name: /etc/systemd/system/getty@tty1.service.d
      file:
        path: /etc/systemd/system/getty@tty1.service.d
        owner: root
        group: root
        mode: "0755"
        state: directory
      become: true
    - name: Auto login configuration
      template:
        src: ./templates/systemd/system/getty@tty1.service.d/override.conf
        dest: /etc/systemd/system/getty@tty1.service.d/override.conf
        owner: root
        group: root
        mode: "0644"
      become: true
    - name: Liquid cooler configuration file
      template:
        src: ./templates/systemd/system/liquidcfg.service
        dest: /etc/systemd/system/liquidcfg.service
        owner: root
        group: root
        mode: "0644"
      become: true
      when:
        - not laptop
        - not vm
    - name: Reload systemd
      systemd:
        daemon_reload: true
      become: true
    - name: Liquid cooler configuration service
      service:
        name: liquidcfg
        state: started
        enabled: true
      become: true
      when:
        - not laptop
        - not vm
    - name: Start & enable pipewire-pulse
      service:
        name: pipewire-pulse
        state: started
        enabled: true
        scope: user
    - name: Start & enable systemd-networkd
      service:
        name: systemd-networkd
        state: started
        enabled: true
      become: true
    - name: Start & enable systemd-resolved
      service:
        name: systemd-resolved
        state: started
        enabled: true
      become: true
    - name: Use systemd-resolved DNS config stub
      file:
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        state: link
      become: true
    - name: Create resolved.conf.d directory
      file:
        path: /etc/systemd/resolved.conf.d
        state: directory
        mode: "0755"
      become: true
    - name: Fallback DNS configuration
      template:
        src: ./templates/systemd/resolved.conf.d/fallback_dns.conf
        dest: /etc/systemd/resolved.conf.d/fallback_dns.conf
        owner: root
        group: root
        mode: "0644"
      become: true
    - name: Create systemd/network directory
      file:
        path: /etc/systemd/network
        state: directory
        mode: "0755"
      become: true
    - name: Remove old Wired network config
      ansible.builtin.file:
        path: /etc/systemd/network/20-wired.network
        state: absent
      become: true
    - name: Network configuration
      template:
        src: ./templates/systemd/network/20-dhcp.network
        dest: /etc/systemd/network/20-dhcp.network
        owner: root
        group: root
        mode: "0644"
      become: true
    - name: Network online wait configuration
      lineinfile:
        path: /etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service
        regexp: "^ExecStart="
        line: "ExecStart=/usr/lib/systemd/systemd-networkd-wait-online --any"
      become: true
    - name: Create iwd directory
      file:
        path: /etc/iwd
        state: directory
        mode: "0755"
      become: true
    - name: Wireless network configuration
      template:
        src: ./templates/iwd/main.conf
        dest: /etc/iwd/main.conf
        owner: root
        group: root
        mode: "0644"
      become: true
    - name: Start & enable iwd
      service:
        name: iwd
        state: started
        enabled: true
      become: true
      when: not vm
    - name: Configure timesyncd
      blockinfile:
        insertafter: "[Time]"
        path: "/etc/systemd/timesyncd.conf"
        mode: "0644"
        block: |
          NTP=au.pool.ntp.org
          FallbackNTP=0.arch.pool.ntp.org 1.arch.pool.ntp.org 2.arch.pool.ntp.org 3.arch.pool.ntp.org
      become: true
    - name: Start & enable timesyncd
      service:
        name: systemd-timesyncd
        state: started
        enabled: true
      become: true
    - name: Network online detection configuration
      template:
        src: ./templates/systemd/user/networkd-wait-online.service
        dest: ~/.config/systemd/user/networkd-wait-online.service
        owner: "{{ ansible_user_id }}"
        group: users
        mode: "0644"
    - name: Geoclue configuration
      template:
        src: ./templates/systemd/user/geoclue-agent.service
        dest: ~/.config/systemd/user/geoclue-agent.service
        owner: "{{ ansible_user_id }}"
        group: users
        mode: "0644"
    - name: Redshift configuration override directory
      file:
        path: ~/.config/systemd/user/redshift.service.d
        owner: "{{ ansible_user_id }}"
        group: users
        mode: "0755"
        state: directory
    - name: Redshift configuration
      template:
        src: ./templates/systemd/user/redshift.service.d/override.conf
        dest: ~/.config/systemd/user/redshift.service.d/override.conf
        owner: "{{ ansible_user_id }}"
        group: users
        mode: "0644"
    - name: Reload systemd user
      systemd:
        daemon_reload: true
        scope: user
    - name: Start & enable network online detection
      systemd:
        name: networkd-wait-online
        state: started
        enabled: true
        scope: user
    - name: Start & enable geoclue-agent
      systemd:
        name: geoclue-agent
        state: started
        enabled: true
        scope: user
    - name: Start & enable redshift
      systemd:
        name: redshift
        state: started
        enabled: true
        scope: user
    - name: Allow fingerprint auth for desired actions
      blockinfile:
        insertafter: "#"
        path: "/etc/pam.d/{{ item }}"
        block: |
          auth sufficient pam_unix.so try_first_pass likeauth nullok
          auth sufficient pam_fprintd.so
      become: true
      loop:
        - sudo
        - login
        - i3lock
      when:
        - laptop
        - not vm
    - name: Remove asdf configuration
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - ~/.asdf
        - ~/.tool-versions
