[workstation]
depends = [
  "graphics",
  "fish",
  "alacritty",
  "git",
  "fd",
  "flameshot",
  "mpv",
  "topgrade",
  "gpg",
  "neovim",
  "i3"
]

[laptop.variables]
font_size = "12.0"
laptop = true

[desktop.variables]
font_size = "16.0"

[graphics.variables.colors16]
base00 = "282c34"
base01 = "353b45"
base02 = "3e4451"
base03 = "545862"
base04 = "565c64"
base05 = "abb2bf"
base06 = "b6bdca"
base07 = "c8ccd4"
base08 = "e06c75"
base09 = "d19a66"
base0a = "e5c07b"
base0b = "98c379"
base0c = "56b6c2"
base0d = "61afef"
base0e = "c678dd"
base0f = "be5046"

[fish.files]
"config/fish" = "~/.config/fish"
"config/starship.toml" = "~/.config/starship.toml"

[alacritty]
depends = ["graphics"]

[alacritty.files]
"config/alacritty/alacritty.yml" = "~/.config/alacritty/alacritty.yml"

[git.files]
"config/git/commitmessage" = "~/.commitmessage"
"config/git/gitconfig" = "~/.gitconfig"
"config/git/gitignore" = "~/.gitignore"

[fd.files]
"config/fdignore" = "~/.fdignore"

[flameshot.files]
"config/flameshot.ini" = "~/.config/flameshot/flameshot.ini"

[mpv.files]
"config/mpv/mpv.conf" = "~/.config/mpv/mpv.conf"

[topgrade.files]
"config/topgrade.toml" = "~/.config/topgrade.toml"

[gpg.files]
"config/gnupg/gpg.conf" = "~/.gnupg/gpg.conf"
"config/gnupg/gpg-agent.conf" = "~/.gnupg/gpg-agent.conf"

[neovim.files]
"config/nvim/lua" = "~/.config/nvim/lua"
"config/nvim/init.lua" = "~/.config/nvim/init.lua"

[redshift.files]
"config/redshift.conf" = "~/.config/redshift/redshift.conf"

[i3.files]
"config/i3status-rust/config.toml" = "~/.config/i3status-rust/config.toml"
"config/i3/config.i3config" = "~/.config/i3/config"
